config/routes.rb
Rails.application.routes.draw do
    root 'sessions#new'

    get '/login' => 'sessions#new', as: 'login'
    post '/login' => 'sessions#create'
    delete '/login' => 'sessions#destroy', as: 'logout'

    resources :users

    resources :workouts do
      resources :movements
    end

  end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_and_belongs_to_many :workouts
  has_many :movements, through: :workouts


  def add_workout(workout)
      self.workouts.push(workout)
  end

  def remove_workout(workout)
      self.workouts.push(workout)
  end

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  has_many :movements, dependent: :destroy
  has_and_belongs_to_many :users


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method(:current_user)

  def authorize
      redirect_to '/login' unless current_user
  end
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  
  def create
    @workout = Workout.find(params[:workout_id])
    @movement = @workout.movements.create(params[:movement].permit(:movement, :reps))

    redirect_to workout_path(@workout)
  end

  def edit
  end

  def destroy
    @movement = Movement.find(params[:id])
    @movement.destroy

    redirect_to workout_path(@workout)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(user_name: params[:user_name])

    if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to(workouts_path, notice: 'Logged in')
    else
        flash.now.alert = "Login failed"
        redirect_to "/login"
    end
  end

    def destroy
        session[:user_id] = nil

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authorize, except: [:index, :new, :create, :show]

  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
    @current_user = current_user
  end

  def new
    @user= User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to "/workouts"
      else
        redirect_to "/users/new"
      end
    end

  def add_workout
    @user = User.find(params[:id])
    @user.add_workout(workout)
  end

    private
    def user_params
        params.require(:user).permit(:user_name, :password, :password_confirmation)
    end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :authorize, except: [:index, :show]
  before_action :find_workout, only: [:show, :edit, :update, :destroy]


  def index
    @workouts = Workout.all.order("Created_at DESC")
  end

  def show
    @workout = Workout.find(params[:id])
  end

  def new
    @workout = Workout.new
  end

  def create
    if @workout = Workout.new(workout_params)
    @workout.save

    current_user.add_workout(@workout)

    redirect_to @workout
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @workout.update(workout_params)
      redirect_to @workout
    else
      render 'edit'
    end
  end

  def destroy
    @workout.destroy
    redirect_to '/workouts'
  end

  private

  def workout_params
    params.require(:workout).permit(:date, :workout, :notes)
  end

  def find_workout
      @workout = Workout.find(params[:id])
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GA FIT CLUB</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="flash">
    <%= flash.notice %>
  <p>
<%= yield %>

</body>
</html>

app/views/movements/_form.html.erb
<div class="movement_form">
<%= simple_form_for([@workout, @workout.movements.build]) do |f| %>
    <%= f.input :movement, input_html: { class: "form-control" } %>
    <%= f.input :reps, input_html: { class: "form-control"} %> <br>

    <div id="movement_button">
    <%= f.button :submit %>
   </div>

</div>
<% end %>

app/views/movements/_movement.html.erb
  <h4 class="show_movement"> Movement Name: <%= movement.movement %>  </h4>
  <h4 class="show_movement"> # Of Reps:  <%= movement.reps %>  </h4>

app/views/users/index.html.erb
<h1 id="leaderboard_header"> Reps Leaderboard </h1>


  <table class="table table-bordered" id="leaderboard">

    <tr>
      <th class="text-center"> Athlete Name </th>
      <th class="text-center"> # of Reps </th>
    </tr>
    <tr>
      <% @user.each do |user| %>
      <td> <%= user.movements.sum("reps") %> </td>
      <td> <%= user.user_name %> </td>
    </tr>
  <% end  %>
  </table>

app/views/users/new.html.erb
<h1 id="headline"> New Athlete </h1>

<div class = "form-group">
<%= simple_form_for(@user, html: {class: 'form-horizontal' }) do |f| %>
  <%= f.input :user_name, label: "User Name" , input_html: { class: "form-control"} %>
  <%= f.input :password, label: "Password", input_html: { class: "form-control"} %>
  <%= f.input :password_confirmation, label: "Confirm Password", input_html: { class: "form-control"} %>
  <br>
  <%= f.button :submit %>
</div>
  <% end %>

app/views/users/show.html.erb
<h1 id="header_user"> <%= @user.user_name %>'s Workouts </h1>

<div class="workout_container">
  <% @user.workouts.each do |w| %>
    <h3> <%= link_to w.date.strftime("%A,%B,%d"), w,{:style=>'color:#d8d624;'} %>  </h3>
    <h4 class="user_workout"> WOD: <%= w.workout %>  </h4>
    <h4 class="user_workout"> Time / Notes: <%= w.notes %>  </h4>
  <% w.movements.each do |m| %>

<h4 class="user_workout"> Completed: <%= m.movement %> - <%= m.reps %>  </h4>
  <% end %>
  <% end %>
</div>

<button class="btn btn-default" id="user_button"> <%= link_to "Back", "/workouts" %> </button>

app/views/workouts/_form.html.erb
<div class="workout_form">

 <%= simple_form_for(@workout, html: {class: 'form-horizontal' }) do |f| %>
    <%= f.input :date, label: "Date" %>
    <%= f.input :workout, label: "WOD", input_html: { class: "form-control"} %>
    <%= f.input :notes, label: "Notes / Time", input_html: { class: "form-control"} %>
    <br>
    <%= f.button :submit, { id: "workout_button"} %>
  <% end %>

</div>

app/views/workouts/edit.html.erb
<h1 id="edit_header"> Edit WOD  <h1>

  <%= render 'form' %>

  <div id="cancel_button">
  <button class="btn btn-default"> <%= link_to "Cancel", "/workouts"  %> </button>
  </div>

app/views/workouts/index.html.erb
<%= image_tag("one_hundred_logo.png", width: '250', height: '75', class: "logo_workout") %>

<div class="workout_container">
<% @workouts.each do |workout| %>
  <% workout.users.each do |u| %>

  <h3><%= link_to workout.date.strftime("%A,%B,%d"), workout,{:style=>'color:#d8d624;'} %> </h3>
  <h4 id="workout_name"> <%= workout.workout%> </h4>
  <h5 id="workout_link"> Completed by: <%= link_to "#{u.user_name}", user_path(u.id)  %> </h5>
<% end %>
<% end %>
</div>

  <button class="btn btn-default" id="new_workout_button"> <%= link_to "Create a new workout", new_workout_path  %> </button>
  <button class="btn btn-default" id="new_workout_button"> <%= link_to "#{current_user.user_name}, logout", logout_path  %> </button>


data: { confirm: "are you sure you want to delete?"}

app/views/workouts/new.html.erb
<h1 id="workout_header"> Create A New Workout  <h1>

  <%= render 'form' %> <br> 
  <button class="btn btn-default" id="new_workout_btn"> <%= link_to "Cancel", "/workouts" %> </button>

app/views/workouts/show.html.erb
<h2 id="show_workout_header"> <%= @workout.date.strftime("%A,%B,%d")%> </h2>

<h4 id="show_wod"> WOD: <%= @workout.workout %>  </h4>
<h4 id="show_notes"> Notes / Time: <%= @workout.notes %>  </h4>


<div id ="button_group">
  <button class="btn btn-default"> <%= link_to "Back", "/workouts" %> </button>
  <button class="btn btn-default"> <%= link_to "Edit" , edit_workout_path(@workout) %>  </button>
  <button class="btn btn-default"> <%= link_to "Delete", workout_path(@workout), method: :delete, data: { confirm: "are you sure you want to delete?"} %>  </button>
</div>


<h3 class="log_workout"> Log your workout </h4>
  <%= render partial: @workout.movements, locals: {workout_id: @workout.id} %>


<h3 class="log_workout"> Add A Movement </h3>
    <%= render "movements/form" %>